# --- CREDENTIALS ---
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "YOUR_DB_PASSWORD"
DB_NAME = "YOUR_DB_NAME"

# --- API KEYS ---
HF_TOKEN = "" 
GEMINI_KEY = "YOUR_GEMINI_API_KEY"
ELEVEN_KEY = "YOUR_ELEVENLABS_API_KEY"

# --- NEW SERVICES ---
NEWS_API_KEY = "YOUR_NEWS_API_KEY"
WEATHER_API_KEY = "YOUR_WEATHER_API_KEY"